"""Forecast domain entity — a persisted, real time-series projection of one
numeric dataset column, generated either directly via the REST API or by
the chat system's forecasting agent (see ADR — milestone 8 forecasting).

Only successful forecasts are persisted, mirroring how the AutoML agent
already treats a failed training attempt: an exception propagates and
callers turn it into an appropriate error (an HTTP 400 for the REST route,
a failed ``AgentRunResult`` for the chat tool) rather than a stored
"failed" row. A ``Forecast`` row is always a real, usable result.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from uuid import UUID

from quantix_api.domain.entities.base import TenantScopedEntity


class ForecastMethod(StrEnum):
    """Which model actually produced the forecast — always recorded and
    surfaced to the caller (REST response and chat output alike) rather
    than left implicit, since the two methods carry very different
    confidence: `HOLT_WINTERS` models trend (optionally damped) with a
    real prediction interval; `LINEAR_TREND` is a plain least-squares
    fallback for series too short for `HOLT_WINTERS` to fit meaningfully,
    with a heuristic (not statistically rigorous) interval.
    """

    HOLT_WINTERS = "holt_winters"
    LINEAR_TREND = "linear_trend"


@dataclass(frozen=True, slots=True)
class ForecastPoint:
    """One projected future value. ``period`` is 1-indexed steps ahead of
    the last historical point — not a calendar date, since the source
    column's actual time unit (daily/weekly/monthly/unlabeled) isn't known.
    """

    period: int
    value: float
    lower: float
    upper: float


@dataclass(
    kw_only=True, eq=False
)  # see base.Entity docstring — required to inherit identity equality
class Forecast(TenantScopedEntity):
    dataset_id: UUID
    created_by_user_id: UUID
    # Set when generated by the chat forecasting agent, None for a
    # standalone REST-created forecast — lets a forecast be traced back to
    # the conversation that produced it without conversations needing to
    # know anything about forecasts.
    conversation_id: UUID | None = None
    target_column: str
    time_column: str | None = None
    method: ForecastMethod
    historical_points: int
    points: list[ForecastPoint] = field(default_factory=list)
